#!/bin/sh
# devtmpfs does not get automounted for initramfs
#/bin/mount -t devtmpfs devtmpfs /dev

# use the /dev/console device node from devtmpfs if possible to not
# confuse glibc's ttyname_r().
# This may fail (E.G. booted with console=), and errors from exec will
# terminate the shell, so use a subshell for the test
if (exec 0</dev/console) 2>/dev/null; then
    exec 0</dev/console
    exec 1>/dev/console
    exec 2>/dev/console
fi

[ -d /dev ] || mkdir -m 0755 /dev
[ -d /sys ] || mkdir /sys
[ -d /proc ] || mkdir /proc
[ -d /tmp ] || mkdir /tmp
[ -d /run ] || mkdir /run
[ -d /root ] || mkdir /root
[ -d /etc ] || mkdir /etc
[ -d /home ] || mkdir /home
[ -d /var  ] || mkdir /var

echo 'root:x:0:0:root:/root:/bin/sh' > /etc/passwd
echo 'root:x:0:' > /etc/group
chmod 644 /etc/passwd
chmod 644 /etc/group

adduser user --disabled-password 2>/dev/null

chown -R root:root /
chmod 700 -R /root
chown user:root /home/user
chmod 777 /home/user
chmod 755 /dev

mount -t proc -o nodev,noexec,nosuid proc /proc
mount -t sysfs -o nodev,noexec,nosuid sysfs /sys
mount -t devtmpfs -o nosuid,mode=0755 udev /dev
mount -t tmpfs -o "noexec,nosuid,size=10%,mode=0755" tmpfs /run

mkdir -p /dev/pts
mkdir -p /var/lock
mount -t devpts -o noexec,nosuid,gid=5,mode=0620 devpts /dev/pts || true

ln -sf /proc/mounts /etc/mtab

echo 1 > /proc/sys/kernel/kptr_restrict
echo 1 > /proc/sys/kernel/dmesg_restrict
echo 1 > /proc/sys/kernel/perf_event_paranoid

insmod k32.ko
chmod 666 /dev/k32
chmod 400 /flag

clear

echo "                                                              "
echo "                                 .--,-\`\`-.                    "
echo "                          ,-.   /   /     '.         ,----,   "
echo "                      ,--/ /|  / ../        ;      .'   .' \\  "
echo "                    ,--. :/ |  \\ \`\`\  .\`-    '   ,----,'    | "
echo "                    :  : ' /    \\___\\/   \\   :   |    :  .  ; "
echo "                    |  '  /          \   :   |   ;    |.'  /  "
echo "                    '  |  :          /  /   /    \`----'/  ;   "
echo "                    |  |   \\         \\  \\   \\      /  ;  /    "
echo "                    '  : |. \    ___ /   :   |    ;  /  /-,   "
echo "                    |  | ' \ \  /   /\   /   :   /  /  /.\`|   "
echo "                    '  : |--'  / ,,/  ',-    . ./__;      :   "
echo "                    ;  |,'     \ ''\        ;  |   :    .'    "
echo "                    '--'        \   \     .'   ;   | .'       "
echo "                                 \`--\`-,,-'     \`---'          "
echo "                                                              "
echo "                                                                                 "
echo "                                                                                 "
echo "                         ,----..                                ___              "
echo "  ,---,      ,--,       /   /   \                             ,--.'|_     .--.,  "
echo ",---.'|    ,--.'|      /   .     :                            |  | :,'  ,--.'  \ "
echo "|   | :    |  |,      .   /   ;.  \   .--.--.                 :  : ' :  |  | /\/ "
echo ":   : :    \`--'_     .   ;   /  \` ;  /  /    '      ,---.   .;__,'  /   :  : :   "
echo ":     |,-. ,' ,'|    ;   |  ; \ ; | |  :  /\`./     /     \  |  |   |    :  | |-, "
echo "|   : '  | '  | |    |   :  | ; | ' |  :  ;_      /    / '  :__,'| :    |  : :/| "
echo "|   |  / : |  | :    .   |  ' ' ' :  \  \    \`.  .    ' /     '  : |__  |  |  .' "
echo "'   : |: | '  : |__  '   ;  \; /  |   \`----.   \ '   ; :__    |  | '.'| '  : '   "
echo "|   | '/ : |  | '.'|  \   \  ',  /   /  /\`--'  / '   | '.'|   ;  :    ; |  | |   "
echo "|   :    | ;  :    ;   ;   :    /   '--'.     /  |   :    :   |  ,   /  |  : \   "
echo "/    \  /  |  ,   /     \   \ .'      \`--'---'    \   \  /     ---\`-'   |  |,'   "
echo "\`-'----'    ---\`-'       \`---\`                     \`----'               \`--'     "
echo "                                                                                 "

setsid cttyhack setuidgid 1000 sh
